module.exports = {
  "id": "olympic-test-slider",
  "viewports": [
    {
      "label": "tablet",
      "width": 768,
      "height": 1024,
    },
  ],
  "resembleOutputOptions": {
    "ignoreAntialiasing": true
  },
  "scenarios": [
    {
      "label": "slider with one slide",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      onReadyScript: `onReady.cjs`,
    },
    {
      "label": "slider with two slides init state",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderSecond.cjs`,
    },
    {
      "label": "slider with two slides after next button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.next", ".btn.next",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderSecond.cjs`,
    },
    {
      "label": "slider with two slides after next and prev button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.next", ".btn.prev",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderSecond.cjs`,
    },
    {
      "label": "slider with two slides after prev button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.prev", ".btn.prev",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderSecond.cjs`,
    },
    {
      "label": "slider with three slides init state",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides after double next button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.next", ".btn.next"
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides after double next and prev button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.next", ".btn.next", ".btn.prev",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides after prev button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.prev",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides after double prev and next button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.prev", ".btn.prev", ".btn.next",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides after loop with next button click",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".btn.next", ".btn.next", ".btn.next",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides paginate then next",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".pagination>button:nth-child(2)",".btn.next",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
    {
      "label": "slider with three slides paginate then prev",
      "url": "http://localhost:3000/slider.html",
      misMatchThreshold: 1,
      requireSameDimensions: true,
      postInteractionWait: 500,
      clickSelectors: [
        ".pagination>button:nth-child(3)", ".btn.prev",
      ],
      onReadyScript: `onReady.cjs`,
      onBeforeScript: `sliderThird.cjs`,
    },
  ],
  fileNameTemplate: '{scenarioLabel}_{viewportLabel}',
  "paths": {
    "bitmaps_reference": "bitmaps_reference/test-pp",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "engine_scripts",
    "html_report": "backstop_data/html_report",
    "json_report": "backstop_data/json_report",
  },
  "report": ["browser", "json"],
  "engine": "puppeteer",
  "engineOptions": {
    "args": ["--no-sandbox"],
    "gotoParameters": {"waitUntil": ["load", "networkidle0"], timeout: 20000},
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}
